// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqmsarlaiatmczyoisrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxbXNhcmxhaWF0bWN6eW9pc3J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjM1NjksImV4cCI6MjA3MDgzOTU2OX0.X6DnhbkDXddCZTg76NOyjsDm6r0oBGyrW-1MEG2cvM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});